# Generated by Django 5.2.10 on 2026-02-03 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(db_index=True, max_length=20)),
                ('loan_type', models.CharField(choices=[('RETAIL', 'Retail Data'), ('COMMERCIAL', 'Commercial Data')], max_length=20)),
                ('dataset_version', models.UUIDField(default=uuid.uuid4)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'external_bank_dataset_state',
                'constraints': [models.UniqueConstraint(fields=('bank_code', 'loan_type'), name='unique_dataset_state')],
            },
        ),
        migrations.CreateModel(
            name='MockLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(db_index=True, max_length=20)),
                ('loan_type', models.CharField(choices=[('RETAIL', 'Retail Data'), ('COMMERCIAL', 'Commercial Data')], max_length=20)),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField()),
                ('dataset_version', models.UUIDField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'external_bank_mock_loan',
                'indexes': [models.Index(fields=['bank_code', 'loan_type'], name='external_ba_bank_co_6b3d23_idx')],
                'constraints': [models.UniqueConstraint(fields=('bank_code', 'loan_type', 'external_id'), name='unique_mock_loan')],
            },
        ),
    ]
