# Generated by Django 5.2.10 on 2026-02-03 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tenant_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('FAILED_VALIDATION', 'Failed Validation')], db_index=True, default='STARTED', max_length=20)),
                ('loan_type', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('record_count', models.IntegerField(default=0)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('invalid_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='BatchError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('error_code', models.CharField(max_length=50)),
                ('field_name', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('raw_excerpt', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='api.batch')),
            ],
            options={
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['batch', 'row_number'], name='api_batcher_batch_i_b2e7b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('loan_type', models.CharField(choices=[('RETAIL', 'Retail Loan'), ('COMMERCIAL', 'Commercial Loan')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='api.client')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'loan_type'], name='api_loan_tenant__fb2b08_idx'), models.Index(fields=['tenant', 'external_id'], name='api_loan_tenant__d6be00_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'external_id', 'loan_type'), name='uniq_tenant_loan')],
            },
        ),
        migrations.CreateModel(
            name='LoanPaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('RETAIL', 'Retail Loan'), ('COMMERCIAL', 'Commercial Loan')], db_index=True, max_length=20)),
                ('loan_external_id', models.CharField(db_index=True, max_length=100)),
                ('installment_number', models.IntegerField(db_index=True)),
                ('scheduled_payment_date', models.DateField(blank=True, null=True)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='api.client')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'loan_type'], name='api_loanpay_tenant__e130a0_idx'), models.Index(fields=['tenant', 'loan_external_id'], name='api_loanpay_tenant__d724ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'loan_type', 'loan_external_id', 'installment_number'), name='uniq_tenant_payment_plan_row')],
            },
        ),
        migrations.CreateModel(
            name='UserTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user',), name='uniq_user_tenant_link')],
            },
        ),
    ]
